### ISSUE TITLE
Use of path dependency from node 0.12.7

### ISSUE THREAD

**Issue by bodnarbm** [tomasbjerre/npm-java-runner#1]
It looks like this library is currently declaring the[ path npm package](https://www.npmjs.com/package/path) a dependency instead of using the default path module built into node. This is creating an issue in my project when trying to update to the latest version of [wiremock](https://www.npmjs.com/package/wiremock) as [good-fences](https://www.npmjs.com/package/good-fences/v/1.1.2) which is detecting references to the builtin `path` module as references to this older npm package.

I was able to determine that the issue was related to this package bringing in the path package from npm

```
❯ npm ls path
backend@1.0.0 <path-on-my-machine>
└─┬ wiremock@2.33.2
  └─┬ npm-java-runner@0.0.17
    └── path@0.12.7
```

Since path is a builtin module to node and the npm package for path is 7 years old and does not match the latest version of path in node, can this dependency be removed from this library?

I am happy to submit a PR to remove it if helpful.

**Comment by tomasbjerre** [comment]
Thanks. I was not aware of the built in module.
I release the Wiremock package with same version as Wiremock. So not really sure if there is much to do but to wait for next Wiremock-version to be released and I will wrap that into a new release of the Wiremock npm-package.

**Comment by bodnarbm** [comment]
Thanks @tomasbjerre! As you noted, it looks like the wiremock npm package.json will need to be updated to pull in the latest version on the next release (right now it stops at 0.0.17 due to semver rules).

But until then I am unblocked by just adding an overrides to my own package.json of

```
"overrides": {
    "npm-java-runner": "^1.0.2"
}
```

So I'm good for now, and look forward to the fix landing without the need for the overrides in the next wiremock release.

**Comment by tomasbjerre** [comment]
Great, thanks again.
